### ISSUE TITLE
Polish particles demo

### ISSUE THREAD

**Issue by paulsonnentag** [paulsonnentag/swip#36]
Current demo has performance problems when adding a lot of particles:
- [X] Instead of hundreds of particles add a single blob when the user presses the screen.
- [x] blobs are interactive, user can drag blobs around
- [x] if user presses down longer a bigger, <strike> slower blob is created </strike>
- [x] if user drags a blob and releases it, the blob will be thrown in the dragged direction
- [x] background color should change based on which cluster the clients is in
- [x] create no blob on swipe (add timeout where blob creation is canceled if user moves touch)

It could look something like this
![](http://www.geisswerks.com/ryan/BLOBS/keep1c.gif)

**Comment by timgrossmann** [comment]
The speed is now determined by the speed of the users drag
