### ISSUE TITLE
devices can't communicate each other

### ISSUE THREAD

**Issue by yoshow** [paulsonnentag/swip#43]
I use two devices with same ip 192.168.10.222:3000,I could visit the application "particles",but two devices couldn't communicate each other.Please tell me how can I deal with this problem. thx.

**Comment by paulsonnentag** [comment]
I don't completely understand your question. The two devices have to be in the same network so they can't have the  same IP address.  You have to start the server on your  computer then you enter the address of the server on each device and it should work. If this doesn't solve your problem please explain what you did exactly.

**Comment by timgrossmann** [comment]
Did you run the `npm install` correctly ?
Did you "Swip" the two devices together correctly ?
Are there any errors in the console when running the server with `npm run particles` ?
Can you touch a single device to create a 'blob' ?

**Comment by yoshow** [comment]
my network env like this
node server ip - 192.168.10.1 
iPhone 6 A - 192.168.3.5 and iPhone 6 B - 192.168.3.6

192.168.10.1 - npm run particles and I can see the message "started server: http://localhost:3000"
iPhone 6 A and iPhone 6 B visit http://192.168.10.1:3000 
i can see color page and touch the phone create a 'blob' 
the blob move itself in phone, but the blob can't move iPhone A to iPhone B like yutube video.

**Comment by yoshow** [comment]
the server and the clients need same network segment?

**Comment by timgrossmann** [comment]
Did you pinch the devices together ? Only If they switch to the same background color they are connected
