### ISSUE TITLE
Phaser examples

### ISSUE THREAD

**Issue by jdnichollsc** [paulsonnentag/swip#45]
Hi man,

It's possible to use **swip.js** with **Phaser Framework**?

Regards, Nicholls

**Comment by paulsonnentag** [comment]
Yes It should work, although it might be a little bit more complicated than just using canvas. Everytime the game state changes an update event is triggered with the new state. With the canvas api it's really easy. We just rerender the whole game and forget about it. If you're using Phaser you would need to figure out what has changed and apply the changes to your Phaser game objects.

``` javascript
var socket = io.connect();

swip.init({ socket: socket, container: document.getElementById('root') }, function (client) {

  client.onUpdate(function (evt) {
    state = evt
    // apply updates to your phaser game here

  });
});
```
