### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by patryk2768** [paulsonnentag/swip#46]
Can you explain me how to install this. Your project is very intresting, but i never was programming in node. Can you add tutorial on Youtube or in detail explain me?

**Comment by m1guelpiedrafita** [comment]
1. Install (node and nmp) [https://nodejs.org/en/download/]
2. Download a (copy of this repo)[https://github.com/paulsonnentag/swip/archive/master.zip] and extract it.
3. Follow the steps in the (installation section)[https://github.com/paulsonnentag/swip#installation].

**Comment by patryk2768** [comment]
1i have it
2 i extract it
3 I do not know how to do it. and I do not understand the instructions never programmed.
Can u explain me third point. Thanks

**Comment by m1guelpiedrafita** [comment]
Windows:
1. Open a comand promt (as administrator)
2. Go to the program folder (do `cd foldername` to open a folder and `cd .. to exit a folder`).
3. Get to the folder where you extracted the program
4. Run `npm install`
5. Move to the example you want to run
6. Run `npm install`
7. Move to the base folder
8. Run `npm run build`

**Comment by patryk2768** [comment]
I must have socket.io?

**Comment by patryk2768** [comment]
![a](https://cloud.githubusercontent.com/assets/23155157/19849120/a111f0b0-9f51-11e6-81f8-dc1e33f268a7.jpg)
thats problem or not?

**Comment by patryk2768** [comment]
Can you send me screenshot step by step what i must do?

**Comment by patryk2768** [comment]
If i write npm run build was appers error

**Comment by m1guelpiedrafita** [comment]
I can not acess my computer, so the screenshot guide isn't possible. Also, can you take an screenshot of the error you get when running `npm run build`?

**Comment by patryk2768** [comment]
![c](https://cloud.githubusercontent.com/assets/23155157/19886797/3cc07760-a025-11e6-88d7-2eb86ae15525.jpg)

**Comment by m1guelpiedrafita** [comment]
Seems like a Swip issue... Open a new issue with that screenshot and the npm-debug.log

**Comment by patryk2768** [comment]
![d](https://cloud.githubusercontent.com/assets/23155157/19888537/7e3b6ef2-a02f-11e6-9d46-f3c014600a06.jpg)

**Comment by paulsonnentag** [comment]
You need to install [webpack](https://github.com/webpack/webpack) as a global depedency. We should add that to the documentation, our bad. 

If you install webpack like this it should work:

``` bash
npm install webpack -g
```

@m1guelpiedrafita thanks for helping out

**Comment by patryk2768** [comment]
@paulsonnentag @m1guelpiedrafita  thanks you
