### ISSUE TITLE
I cant join to localhost in my phone

### ISSUE THREAD

**Issue by patryk2768** [paulsonnentag/swip#47]
Server is working if i go to http://localhost:3000\ on my computer its working. In my phone is write This site is unreachble Localhost server refused connection. can you help me?

**Comment by timgrossmann** [comment]
You have to use the IP of your computer on the phones.
Localhost is always the current devices IP. 

e.g.
computer localhost -> 192.168.178.1:3000
phone localhost -> 192.168.178.2:3000

on your computer use localhost:3000
on your phone use 192.168.178.1:3000

**Comment by patryk2768** [comment]
server took too long to answer

**Comment by timgrossmann** [comment]
You have to use the ip of your Computer.
What operating system do you use ?

**Comment by patryk2768** [comment]
OK sorry i missclick your project was so great thanks you so much

**Comment by timgrossmann** [comment]
Does it work now ?

**Comment by patryk2768** [comment]
yes

**Comment by timgrossmann** [comment]
Perfect.
Thank you for your patience.

Happy Swipping ;)
